package dev.pointandshoot

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class Dl3ParserTest {

    @Test
    fun `parses identity 17-cube at 12-bit precision`() {
        val text = buildIdentity3dl(size = 17, maxValue = 4095)
        val lut = LutPipeline.parseDl3(text)
        assertEquals(17, lut.size)
        // Spot-check identity at the corners.
        assertSampleEquals(lut, 0, 0, 0, 0f, 0f, 0f, eps = 1e-3f)
        assertSampleEquals(lut, 16, 0, 0, 1f, 0f, 0f, eps = 1e-3f)
        assertSampleEquals(lut, 0, 16, 0, 0f, 1f, 0f, eps = 1e-3f)
        assertSampleEquals(lut, 0, 0, 16, 0f, 0f, 1f, eps = 1e-3f)
        assertSampleEquals(lut, 16, 16, 16, 1f, 1f, 1f, eps = 1e-3f)
    }

    @Test
    fun `parses identity 33-cube at 16-bit precision`() {
        val text = buildIdentity3dl(size = 33, maxValue = 65535)
        val lut = LutPipeline.parseDl3(text)
        assertEquals(33, lut.size)
        // Linear ramp: r=8 / (size-1) = 0.25 expected at index (8, 0, 0).
        assertSampleEquals(lut, 8, 0, 0, 0.25f, 0f, 0f, eps = 1e-3f)
    }

    @Test
    fun `tolerates leading comment + Mesh header lines`() {
        val text = buildString {
            appendLine("# Generated by Lustre 2026.0")
            appendLine("# Mesh 12 12")
            append(buildIdentity3dl(size = 17, maxValue = 4095))
        }
        val lut = LutPipeline.parseDl3(text)
        assertEquals(17, lut.size)
    }

    @Test
    fun `rejects unsupported shaper size`() {
        val text = buildIdentity3dl(size = 5, maxValue = 1023)
        // size=5 is not in Lut3D.SUPPORTED_SIZES.
        try {
            LutPipeline.parseDl3(text)
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("Unsupported 3DL shaper size"))
        }
    }

    @Test
    fun `rejects non-uniform shaper`() {
        val sb = StringBuilder()
        // 17-entry shaper but with a deliberate non-uniform jump.
        val shaper = (0 until 17).map { it * 256 }.toMutableList()
        shaper[8] = shaper[8] + 200 // 4-bit jump that exceeds the 1-step tolerance
        sb.appendLine(shaper.joinToString(" "))
        for (b in 0 until 17) for (g in 0 until 17) for (r in 0 until 17) {
            sb.appendLine("$r $g $b")
        }
        try {
            LutPipeline.parseDl3(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("non-uniform"))
        }
    }

    @Test
    fun `rejects empty input`() {
        try {
            LutPipeline.parseDl3("# only comments here\n# nothing else\n")
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("no integer rows"))
        }
    }

    @Test
    fun `rejects body row with wrong arity`() {
        val sb = StringBuilder()
        // Valid 17-entry shaper, then a malformed first body row.
        sb.appendLine((0 until 17).map { it * 256 }.joinToString(" "))
        sb.appendLine("0 0") // arity=2 should fail
        try {
            LutPipeline.parseDl3(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            // 17 ints in a 2-int row: parser sees this as a shaper-of-2 size mismatch
            // OR a malformed row 0 - either is acceptable.
            assertTrue(e.message ?: "", (e.message ?: "").isNotEmpty())
        }
    }

    @Test
    fun `validator routes 3dl text to parseDl3`() {
        val text = buildIdentity3dl(size = 17, maxValue = 4095)
        val result = LutImportValidator.validate(text)
        assertTrue("expected Success, got $result", result is LutImportValidator.Result.Success)
    }

    @Test
    fun `validator sniffs format - cube wins on LUT_3D_SIZE`() {
        val cubeText = "LUT_3D_SIZE 17\nDOMAIN_MIN 0 0 0\nDOMAIN_MAX 1 1 1\n" +
            buildString { for (i in 0 until 17 * 17 * 17) appendLine("0.5 0.5 0.5") }
        assertEquals(LutImportValidator.Format.Cube, LutImportValidator.sniffFormat(cubeText))
    }

    @Test
    fun `validator sniffs format - 3dl detected from integer-only first line`() {
        val text = buildIdentity3dl(size = 17, maxValue = 4095)
        assertEquals(LutImportValidator.Format.Dl3, LutImportValidator.sniffFormat(text))
    }

    @Test
    fun `validator surfaces unsupported size as UnsupportedSize category`() {
        val text = buildIdentity3dl(size = 5, maxValue = 1023)
        val result = LutImportValidator.validateForFormat(text, LutImportValidator.Format.Dl3)
        assertTrue("expected Failure, got $result", result is LutImportValidator.Result.Failure)
        assertEquals(
            LutImportValidator.FailureCategory.UnsupportedSize,
            (result as LutImportValidator.Result.Failure).category,
        )
    }

    @Test
    fun `validator surfaces empty 3dl as MalformedHeader category`() {
        val text = "# nothing\n"
        val result = LutImportValidator.validateForFormat(text, LutImportValidator.Format.Dl3)
        assertTrue("expected Failure", result is LutImportValidator.Result.Failure)
        assertEquals(
            LutImportValidator.FailureCategory.MalformedHeader,
            (result as LutImportValidator.Result.Failure).category,
        )
    }

    private fun assertSampleEquals(
        lut: Lut3D,
        r: Int, g: Int, b: Int,
        expR: Float, expG: Float, expB: Float,
        eps: Float,
    ) {
        val idx = ((b * lut.size + g) * lut.size + r) * 3
        assertEquals("R at ($r,$g,$b)", expR, lut.samples[idx], eps)
        assertEquals("G at ($r,$g,$b)", expG, lut.samples[idx + 1], eps)
        assertEquals("B at ($r,$g,$b)", expB, lut.samples[idx + 2], eps)
    }

    /**
     * Generate an identity 3DL with the given grid size and integer
     * resolution. The shaper is a uniform ramp from 0 to maxValue;
     * each body row is the integer-coded RGB at the corresponding
     * grid coordinate. R varies fastest.
     */
    private fun buildIdentity3dl(size: Int, maxValue: Int): String {
        val sb = StringBuilder()
        val shaper = (0 until size).map { (it.toDouble() * maxValue / (size - 1)).toInt() }
        sb.appendLine(shaper.joinToString(" "))
        for (b in 0 until size) {
            for (g in 0 until size) {
                for (r in 0 until size) {
                    val rv = (r.toDouble() * maxValue / (size - 1)).toInt()
                    val gv = (g.toDouble() * maxValue / (size - 1)).toInt()
                    val bv = (b.toDouble() * maxValue / (size - 1)).toInt()
                    sb.appendLine("$rv $gv $bv")
                }
            }
        }
        return sb.toString()
    }
}
