package dev.pointandshoot

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class Spi3dParserTest {

    @Test
    fun `parses identity 17-cube`() {
        val text = buildIdentitySpi3d(size = 17)
        val lut = LutPipeline.parseSpi3d(text)
        assertEquals(17, lut.size)
        assertSampleEquals(lut, 0, 0, 0, 0f, 0f, 0f, eps = 1e-5f)
        assertSampleEquals(lut, 16, 0, 0, 1f, 0f, 0f, eps = 1e-5f)
        assertSampleEquals(lut, 16, 16, 16, 1f, 1f, 1f, eps = 1e-5f)
    }

    @Test
    fun `parses identity 33-cube`() {
        val text = buildIdentitySpi3d(size = 33)
        val lut = LutPipeline.parseSpi3d(text)
        assertEquals(33, lut.size)
        assertSampleEquals(lut, 8, 0, 0, 8f / 32f, 0f, 0f, eps = 1e-5f)
    }

    @Test
    fun `tolerates leading comments`() {
        val text = buildString {
            appendLine("# Generated by Imageworks")
            appendLine("# Some metadata: foo=bar")
            append(buildIdentitySpi3d(size = 17))
        }
        val lut = LutPipeline.parseSpi3d(text)
        assertEquals(17, lut.size)
    }

    @Test
    fun `accepts arbitrary cell ordering`() {
        // Build an identity LUT but emit body rows in B-fastest order
        // (default builder is R-fastest). The parser must place each
        // row by index, not by file order.
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("17 17 17")
        for (r in 0 until 17) {
            for (g in 0 until 17) {
                for (b in 0 until 17) {
                    val rf = r / 16f
                    val gf = g / 16f
                    val bf = b / 16f
                    sb.appendLine("$r $g $b $rf $gf $bf")
                }
            }
        }
        val lut = LutPipeline.parseSpi3d(sb.toString())
        assertEquals(17, lut.size)
        // Spot-check that B-axis got placed correctly (which would fail
        // if the parser used file order rather than indices).
        assertSampleEquals(lut, 0, 0, 16, 0f, 0f, 1f, eps = 1e-5f)
    }

    @Test
    fun `rejects missing SPILUT header`() {
        val sb = StringBuilder()
        sb.appendLine("3 3")
        sb.appendLine("17 17 17")
        for (i in 0 until 17 * 17 * 17) sb.appendLine("0 0 0 0.5 0.5 0.5")
        try {
            LutPipeline.parseSpi3d(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("SPILUT"))
        }
    }

    @Test
    fun `rejects 1D variant via 1 1 dim line`() {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("1 1")
        sb.appendLine("17 17 17")
        for (i in 0 until 17 * 17 * 17) sb.appendLine("0 0 0 0.5 0.5 0.5")
        try {
            LutPipeline.parseSpi3d(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("1D variants"))
        }
    }

    @Test
    fun `rejects non-cubic LUTs`() {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("17 33 17")
        try {
            LutPipeline.parseSpi3d(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("cubic"))
        }
    }

    @Test
    fun `rejects unsupported sizes`() {
        // 5 is a perfectly valid spi3d size but not in our SUPPORTED_SIZES.
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("5 5 5")
        for (i in 0 until 5 * 5 * 5) sb.appendLine("0 0 0 0.5 0.5 0.5")
        try {
            LutPipeline.parseSpi3d(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("Unsupported spi3d size"))
        }
    }

    @Test
    fun `rejects body row with wrong arity`() {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("17 17 17")
        // First body row malformed (only 5 tokens).
        sb.appendLine("0 0 0 0.5 0.5")
        for (i in 1 until 17 * 17 * 17) sb.appendLine("0 0 0 0.5 0.5 0.5")
        try {
            LutPipeline.parseSpi3d(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("body row"))
        }
    }

    @Test
    fun `rejects out-of-range index`() {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("17 17 17")
        // 17 is out of range [0, 16] for size=17.
        sb.appendLine("17 0 0 1.0 0.0 0.0")
        for (i in 1 until 17 * 17 * 17) sb.appendLine("0 0 0 0.5 0.5 0.5")
        try {
            LutPipeline.parseSpi3d(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("out of range"))
        }
    }

    @Test
    fun `rejects duplicate cells`() {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("17 17 17")
        // First two body rows both target (0, 0, 0).
        sb.appendLine("0 0 0 0.0 0.0 0.0")
        sb.appendLine("0 0 0 1.0 1.0 1.0")
        // Pad remaining rows to reach the expected count - they will fail
        // before completion but we still need the body length to pass the
        // initial size check.
        for (i in 2 until 17 * 17 * 17) sb.appendLine("0 0 0 0.5 0.5 0.5")
        try {
            LutPipeline.parseSpi3d(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("duplicate"))
        }
    }

    @Test
    fun `rejects body that is too short`() {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("17 17 17")
        // Only 1 body row.
        sb.appendLine("0 0 0 0.0 0.0 0.0")
        try {
            LutPipeline.parseSpi3d(sb.toString())
            org.junit.Assert.fail("expected IllegalArgumentException")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message ?: "", (e.message ?: "").contains("body has"))
        }
    }

    @Test
    fun `validator routes spi3d text to parseSpi3d`() {
        val text = buildIdentitySpi3d(size = 17)
        val result = LutImportValidator.validate(text)
        assertTrue("expected Success, got $result", result is LutImportValidator.Result.Success)
    }

    @Test
    fun `sniffer picks Spi3d on SPILUT header`() {
        val text = buildIdentitySpi3d(size = 17)
        assertEquals(LutImportValidator.Format.Spi3d, LutImportValidator.sniffFormat(text))
    }

    @Test
    fun `validator surfaces 1D variant as OneDLut category`() {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("1 1")
        sb.appendLine("17 17 17")
        for (i in 0 until 17 * 17 * 17) sb.appendLine("0 0 0 0.5 0.5 0.5")
        val result = LutImportValidator.validateForFormat(sb.toString(), LutImportValidator.Format.Spi3d)
        assertTrue(result is LutImportValidator.Result.Failure)
        assertEquals(
            LutImportValidator.FailureCategory.OneDLut,
            (result as LutImportValidator.Result.Failure).category,
        )
    }

    @Test
    fun `validator surfaces unsupported size as UnsupportedSize`() {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("9 9 9")
        for (i in 0 until 9 * 9 * 9) sb.appendLine("0 0 0 0.5 0.5 0.5")
        val result = LutImportValidator.validateForFormat(sb.toString(), LutImportValidator.Format.Spi3d)
        assertTrue(result is LutImportValidator.Result.Failure)
        assertEquals(
            LutImportValidator.FailureCategory.UnsupportedSize,
            (result as LutImportValidator.Result.Failure).category,
        )
    }

    private fun assertSampleEquals(
        lut: Lut3D,
        r: Int, g: Int, b: Int,
        expR: Float, expG: Float, expB: Float,
        eps: Float,
    ) {
        val idx = ((b * lut.size + g) * lut.size + r) * 3
        assertEquals("R at ($r,$g,$b)", expR, lut.samples[idx], eps)
        assertEquals("G at ($r,$g,$b)", expG, lut.samples[idx + 1], eps)
        assertEquals("B at ($r,$g,$b)", expB, lut.samples[idx + 2], eps)
    }

    /**
     * Generate an identity `.spi3d` of the given size with R-fastest body
     * ordering. Float precision is float32 (the spi3d format is float-text).
     */
    private fun buildIdentitySpi3d(size: Int): String {
        val sb = StringBuilder()
        sb.appendLine("SPILUT 1.0")
        sb.appendLine("3 3")
        sb.appendLine("$size $size $size")
        val invMax = 1f / (size - 1)
        for (b in 0 until size) {
            for (g in 0 until size) {
                for (r in 0 until size) {
                    sb.appendLine("$r $g $b ${r * invMax} ${g * invMax} ${b * invMax}")
                }
            }
        }
        return sb.toString()
    }
}
