#Requires -Version 5.1
<#
.SYNOPSIS
  Create a local production keystore + keystore.properties, optionally upload GitHub Actions secrets.

.DESCRIPTION
  Idempotent. If release.keystore and a filled keystore.properties already exist, this script
  does not generate a new identity. Use -ForceCreate only when you intend to replace the key.

  Never commits the keystore or properties file. GitHub secrets use the names required by
  .github/workflows/build-signed.yml.

.PARAMETER ForceCreate
  Replace an existing keystore (destructive for upgrade identity).

.PARAMETER SetGitHubSecrets
  Upload ANDROID_KEYSTORE_BASE64 / PASSWORD / ALIAS / KEY_PASSWORD via gh.

.PARAMETER UpdateExpectedJson
  Write alias + SHA-256 into scripts/pns_keystore_expected.json (safe to commit).
#>
param(
    [switch]$ForceCreate,
    [switch]$SetGitHubSecrets,
    [switch]$UpdateExpectedJson
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. "$PSScriptRoot\pns_release_naming.ps1"

$repoRoot = Split-Path -Parent $PSScriptRoot
$keystorePath = Join-Path $repoRoot "release.keystore"
$propsPath = Join-Path $repoRoot "keystore.properties"
$expectedPath = Join-Path $PSScriptRoot "pns_keystore_expected.json"
$alias = "pns-release"

function Get-PnsJdkBin {
    $jdk = & (Join-Path $PSScriptRoot "pns_java_home.ps1") -EmitPath
    if ([string]::IsNullOrWhiteSpace($jdk)) {
        throw "Could not resolve a JDK. Run scripts/pns_java_home.ps1 -ListCandidates."
    }
    $keytool = Join-Path $jdk "bin\keytool.exe"
    if (-not (Test-Path -LiteralPath $keytool)) {
        $keytool = Join-Path $jdk "bin\keytool"
    }
    if (-not (Test-Path -LiteralPath $keytool)) {
        throw "keytool not found under $jdk"
    }
    return $keytool
}

function New-PnsStorePassword {
    $bytes = New-Object byte[] 24
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }
    return ([Convert]::ToBase64String($bytes) -replace '[+/=]', 'x')
}

function Write-PnsKeystoreProperties([string]$Password) {
    $body = @"
# Generated by scripts/pns_release_signing_bootstrap.ps1 — gitignored. Do not commit.
storeFile=release.keystore
storePassword=$Password
keyAlias=$alias
keyPassword=$Password
"@
    [System.IO.File]::WriteAllText($propsPath, $body, (New-Object System.Text.UTF8Encoding $false))
}

function Get-PnsKeystoreSha256([string]$Keytool, [string]$Password) {
    $listing = & $Keytool -list -v -keystore $keystorePath -alias $alias -storepass $Password 2>&1 | Out-String
    if ($listing -notmatch 'SHA256:\s*([0-9A-Fa-f:]+)') {
        throw "Could not parse SHA-256 from keytool -list"
    }
    return $Matches[1].ToUpperInvariant()
}

$alreadyReady = Test-PnsReleaseSigningConfigured -RepoRoot $repoRoot
if ($alreadyReady -and -not $ForceCreate) {
    Write-Host "[pns_release_signing_bootstrap] Existing production keystore is ready."
} else {
    if ((Test-Path -LiteralPath $keystorePath) -and -not $ForceCreate) {
        throw "release.keystore exists but keystore.properties is incomplete. Fix the properties file or pass -ForceCreate."
    }
    if ($ForceCreate -and (Test-Path -LiteralPath $keystorePath)) {
        Remove-Item -LiteralPath $keystorePath -Force
    }

    $keytool = Get-PnsJdkBin
    $password = New-PnsStorePassword
    Write-Host "[pns_release_signing_bootstrap] Generating PKCS12 keystore at release.keystore"
    & $keytool -genkeypair -keystore $keystorePath -alias $alias `
        -keyalg RSA -keysize 4096 -validity 36500 -storetype PKCS12 `
        -storepass $password -keypass $password `
        -dname "CN=Point and Shoot, OU=Release, O=Point and Shoot, C=US"
    if ($LASTEXITCODE -ne 0) {
        throw "keytool -genkeypair failed"
    }
    Write-PnsKeystoreProperties -Password $password
    Write-Host "[pns_release_signing_bootstrap] Wrote gitignored keystore.properties. Back that file up; it is the only local copy of the password."
}

if (-not (Test-PnsReleaseSigningConfigured -RepoRoot $repoRoot)) {
    throw "Signing still not configured after bootstrap."
}

$map = @{}
foreach ($line in Get-Content -LiteralPath $propsPath) {
    if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
    $parts = $line -split '=', 2
    $map[$parts[0].Trim()] = $parts[1].Trim()
}
$storePassword = [string]$map['storePassword']
$keytool = Get-PnsJdkBin
$sha = Get-PnsKeystoreSha256 -Keytool $keytool -Password $storePassword
Write-Host "[pns_release_signing_bootstrap] alias=$alias sha256=$sha"

if ($UpdateExpectedJson) {
    $expected = @{
        alias = $alias
        sha256 = $sha
        note = "Host-only gate; SHA-256 from keytool -list -v on maintainer release.keystore"
    } | ConvertTo-Json
    [System.IO.File]::WriteAllText($expectedPath, $expected + "`n", (New-Object System.Text.UTF8Encoding $false))
    Write-Host "[pns_release_signing_bootstrap] Updated $expectedPath"
}

if ($SetGitHubSecrets) {
    $gh = Get-Command gh -ErrorAction SilentlyContinue
    if (-not $gh) { throw "gh CLI is required for -SetGitHubSecrets" }
    $bytes = [System.IO.File]::ReadAllBytes($keystorePath)
    $b64 = [Convert]::ToBase64String($bytes)
    $b64 | & gh secret set ANDROID_KEYSTORE_BASE64
    $storePassword | & gh secret set ANDROID_KEYSTORE_PASSWORD
    $alias | & gh secret set ANDROID_KEY_ALIAS
    $storePassword | & gh secret set ANDROID_KEY_PASSWORD
    Write-Host "[pns_release_signing_bootstrap] Set GitHub Actions signing secrets (4)."
}

Write-Host "[pns_release_signing_bootstrap] DONE"
exit 0
