package dev.pointandshoot.fleet

import org.json.JSONObject

/** Master capability taxonomy (Milestone **17.1** + **18.1** expansion). */
object CameraCapabilityCatalog {
    const val CATALOG_VERSION: Int = 6

    enum class SourceLayer(val label: String) {
        Camera2("Camera2"),
        CameraX("CameraX"),
        HalEncoder("HAL/encoder"),
        Product("Product"),
        Root("Root"),
    }

    enum class VisibilityPolicy {
        HideWhenUnavailable,
        RootOnly,
        ShowDisabledEngineering,
        AlwaysShow,
    }

    enum class AppStatus {
        Shipped,
        Partial,
        ProbeOnly,
        Planned,
        NotApplicable,
    }

    data class CatalogRow(
        val id: String,
        val displayName: String,
        val category: String,
        val sourceLayer: SourceLayer,
        val keywords: String = "",
        val visibilityPolicy: VisibilityPolicy = VisibilityPolicy.HideWhenUnavailable,
        val appStatus: AppStatus = AppStatus.Shipped,
        val surfacing: List<String> = emptyList(),
        val rootOnly: Boolean = false,
        val sweepSkipReason: String? = null,
        val consumerImpact: FleetParitySweep.ConsumerImpact? = null,
        val parityProofScript: String? = null,
        val closureEffort: String? = null,
        val buildPlanSprint: String? = null,
        val humanOnly: Boolean = false,
    )

    data class EvaluatedRow(
        val row: CatalogRow,
        val deviceSupported: Boolean,
        val sessionOk: Boolean? = null,
        val detail: String = "",
    ) {
        fun toJson(): JSONObject =
            JSONObject().apply {
                put("id", row.id)
                put("displayName", row.displayName)
                put("category", row.category)
                put("sourceLayer", row.sourceLayer.label)
                put("deviceSupported", deviceSupported)
                put("appStatus", row.appStatus.name)
                put("appShipped", row.appStatus == AppStatus.Shipped || row.appStatus == AppStatus.Partial)
                put("rootOnly", row.rootOnly)
                put("visibilityPolicy", row.visibilityPolicy.name)
                if (sessionOk != null) put("sessionOk", sessionOk)
                if (row.surfacing.isNotEmpty()) put("surfacing", row.surfacing)
                if (detail.isNotEmpty()) put("detail", detail)
                row.sweepSkipReason?.let { put("sweepSkipReason", it) }
                row.parityProofScript?.let { put("parityProofScript", it) }
                row.closureEffort?.let { put("closureEffort", it) }
                row.buildPlanSprint?.let { put("buildPlanSprint", it) }
                if (row.humanOnly) put("humanOnly", true)
                put("consumerImpact", FleetParityConsumerImpact.resolve(row).name)
            }
    }

    private val baseRegistry: List<CatalogRow> =
        listOf(
            CatalogRow("raw.dng", "RAW DNG capture", "Still capture", SourceLayer.Product, "raw dng still", surfacing = listOf("dial_H", "settings"), humanOnly = true, parityProofScript = "pns_aux_dng_capture_analyze.ps1", buildPlanSprint = "21.11"),
            CatalogRow("raw.ultra_max", "Ultra-Max imaging profile", "Still capture", SourceLayer.Product, "ultra max 12bit"),
            CatalogRow("still.bracket", "Exposure bracketing (BKT dial)", "Still capture", SourceLayer.Product, "bracket bkt", surfacing = listOf("mode_dial")),
            CatalogRow("still.zsl", "ZSL still capture", "Still capture", SourceLayer.Camera2, "zsl zero shutter lag"),
            CatalogRow(
                "still.resolution_maximum_map",
                "Maximum-resolution stream map advertised",
                "Still capture",
                SourceLayer.Camera2,
                "max resolution map streamConfigurationMapMaximumResolution",
                appStatus = AppStatus.ProbeOnly,
                consumerImpact = FleetParitySweep.ConsumerImpact.SHIP_BLOCKER,
            ),
            CatalogRow(
                "still.hidden_highres",
                "High-res larger than default Camera2 map",
                "Still capture",
                SourceLayer.Camera2,
                "hidden highres default map",
                appStatus = AppStatus.ProbeOnly,
                consumerImpact = FleetParitySweep.ConsumerImpact.SHIP_BLOCKER,
            ),
            CatalogRow("still.avif", "10-bit AVIF still", "Still capture", SourceLayer.Product, "avif hdr 10bit"),
            CatalogRow(
                "still.jxl",
                "JPEG XL still export",
                "Still capture",
                SourceLayer.Product,
                "jxl jpegxl",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_still_export_verify.ps1",
                buildPlanSprint = "30.1",
            ),
            CatalogRow("still.nightscape", "Nightscape stacking", "Still capture", SourceLayer.Product, "nightscape"),
            CatalogRow("still.intervalometer", "Intervalometer", "Still capture", SourceLayer.Product, "intervalometer timelapse"),
            CatalogRow("video.h264", "H.264 video", "Video", SourceLayer.HalEncoder, "h264 avc", surfacing = listOf("format_picker")),
            CatalogRow("video.hevc", "HEVC video", "Video", SourceLayer.HalEncoder, "hevc h265", surfacing = listOf("format_picker")),
            CatalogRow(
                "video.av1",
                "AV1 video",
                "Video",
                SourceLayer.HalEncoder,
                "av1",
                appStatus = AppStatus.Partial,
                parityProofScript = "pns_av1_parity_verify.ps1",
                buildPlanSprint = "30.2",
            ),
            CatalogRow(
                "video.hfr",
                "High-speed video (120+ fps)",
                "Video",
                SourceLayer.Camera2,
                "hfr 120 240 480",
                appStatus = AppStatus.Shipped,
                surfacing = listOf("fps_rail", "format_picker"),
                parityProofScript = "pns_hfr_fps_parity_verify.ps1",
                buildPlanSprint = "30.2",
            ),
            CatalogRow("video.regular.1080p30", "1080p @ 30 fps (regular)", "Video", SourceLayer.HalEncoder, "1080p 30fps", surfacing = listOf("format_picker")),
            CatalogRow(
                "video.4k_regular",
                "4K @ 30 fps (regular)",
                "Video",
                SourceLayer.HalEncoder,
                "4k 3840 2160 30fps",
                surfacing = listOf("format_picker"),
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_4k_regular_verify.ps1",
                buildPlanSprint = "30.2",
            ),
            CatalogRow("video.dcg_hdr", "HDR / DCG video", "Video", SourceLayer.Camera2, "dcg hdr10"),
            CatalogRow(
                "video.raw",
                "RAW video",
                "Video",
                SourceLayer.Product,
                "raw video",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_raw_video_verify.ps1",
                buildPlanSprint = "30.2",
            ),
            CatalogRow(
                "video.raw_picker",
                "RAW video in format picker",
                "Video",
                SourceLayer.Product,
                "raw mcraw picker",
                appStatus = AppStatus.Shipped,
                surfacing = listOf("format_picker"),
                parityProofScript = "pns_raw_video_verify.ps1",
                buildPlanSprint = "30.2",
            ),
            CatalogRow(
                "video.dual",
                "Dual video composite",
                "Video",
                SourceLayer.Product,
                "dual video",
                appStatus = AppStatus.Shipped,
                surfacing = listOf("mode_dial"),
                parityProofScript = "pns_dual_video_verify.ps1",
                buildPlanSprint = "30.3",
            ),
            CatalogRow("video.timelapse", "Time lapse video", "Video", SourceLayer.Product, "timelapse"),
            CatalogRow("face.detect", "Face detection", "Face & AF", SourceLayer.Camera2, "face detect"),
            CatalogRow("face.eye_af", "Eye-AF overlay", "Face & AF", SourceLayer.Product, "eye af", surfacing = listOf("qs_grid", "settings")),
            CatalogRow("face.priority_ae", "Face-priority AE", "Face & AF", SourceLayer.Product, "face priority ae"),
            CatalogRow("af.manual", "Manual focus (M dial)", "Face & AF", SourceLayer.Camera2, "manual focus", surfacing = listOf("mode_dial")),
            CatalogRow("af.rack", "Rack focus pull", "Face & AF", SourceLayer.Product, "rack focus"),
            CatalogRow("af.macro", "Super Macro", "Face & AF", SourceLayer.Product, "macro", surfacing = listOf("mode_dial")),
            CatalogRow("lens.multi", "Focal slots / multi-cam", "Lens", SourceLayer.Product, "focal uw tele", surfacing = listOf("focal_row")),
            CatalogRow("lens.ois", "Optical stabilization", "Lens", SourceLayer.Camera2, "ois", surfacing = listOf("settings")),
            CatalogRow("lens.eis", "Electronic stabilization", "Lens", SourceLayer.Camera2, "eis", surfacing = listOf("settings")),
            CatalogRow(
                "lens.aperture",
                "Lens aperture readout (F chip)",
                "Lens",
                SourceLayer.Camera2,
                "aperture f-number lens",
                surfacing = listOf("readout"),
            ),
            CatalogRow(
                "lens.variable_aperture",
                "Variable aperture (dual iris)",
                "Lens",
                SourceLayer.Camera2,
                "variable aperture dual iris f2 f4",
                surfacing = listOf("readout"),
            ),
            CatalogRow("hud.zebra", "Zebra / false color", "Preview HUD", SourceLayer.Product, "zebra false color", surfacing = listOf("qs_grid")),
            CatalogRow("hud.histogram", "Histogram", "Preview HUD", SourceLayer.Product, "histogram", surfacing = listOf("settings")),
            CatalogRow("hud.highlight_meter", "Highlight metering (H)", "Preview HUD", SourceLayer.Product, "highlight h dial", surfacing = listOf("mode_dial")),
            CatalogRow("hud.focus_peaking", "Focus peaking", "Preview HUD", SourceLayer.Product, "peaking"),
            CatalogRow(
                "preview.qr",
                "QR scan mode",
                "Preview HUD",
                SourceLayer.Product,
                "qr scan",
                visibilityPolicy = VisibilityPolicy.AlwaysShow,
                surfacing = listOf("mode_dial"),
            ),
            CatalogRow("camerax.night", "CameraX NIGHT", "CameraX", SourceLayer.CameraX, "night", appStatus = AppStatus.ProbeOnly, visibilityPolicy = VisibilityPolicy.ShowDisabledEngineering),
            CatalogRow("camerax.bokeh", "CameraX BOKEH", "CameraX", SourceLayer.CameraX, "bokeh", appStatus = AppStatus.ProbeOnly, visibilityPolicy = VisibilityPolicy.ShowDisabledEngineering),
            CatalogRow("camerax.hdr", "CameraX HDR", "CameraX", SourceLayer.CameraX, "hdr extension", appStatus = AppStatus.ProbeOnly, visibilityPolicy = VisibilityPolicy.ShowDisabledEngineering),
            CatalogRow(
                "product.oem_app_manual_smoke",
                "OEM camera app manual smoke",
                "Product",
                SourceLayer.Product,
                "oem stock camera manual checklist",
                appStatus = AppStatus.ProbeOnly,
                humanOnly = true,
                consumerImpact = FleetParitySweep.ConsumerImpact.INFORMATIONAL,
            ),
            CatalogRow("root.vendor_keys", "Vendor key probe", "Root", SourceLayer.Root, "root vendor", rootOnly = true, visibilityPolicy = VisibilityPolicy.RootOnly, appStatus = AppStatus.ProbeOnly),
            CatalogRow("root.cpu_governor", "CPU governor pin", "Root", SourceLayer.Root, "root cpu", rootOnly = true, visibilityPolicy = VisibilityPolicy.RootOnly, appStatus = AppStatus.ProbeOnly),
            CatalogRow("root.hfr_unlock", "HFR above matrix ceiling", "Root", SourceLayer.Root, "root hfr fps", rootOnly = true, visibilityPolicy = VisibilityPolicy.RootOnly, surfacing = listOf("fps_rail")),
            CatalogRow(
                "root.max_res_unlock_cph2583",
                "Max-resolution unlock lane (CPH2583)",
                "Root",
                SourceLayer.Root,
                "root max resolution unlock qcfa",
                rootOnly = true,
                visibilityPolicy = VisibilityPolicy.RootOnly,
                appStatus = AppStatus.ProbeOnly,
                surfacing = listOf("settings"),
                parityProofScript = "pns_still_resolution_mode_verify.ps1",
                buildPlanSprint = "max_res_unlock",
                sweepSkipReason = "probe_only_inventory",
            ),
            CatalogRow("fleet.matrix", "Device capability matrix", "Fleet", SourceLayer.Product, "fleet matrix", visibilityPolicy = VisibilityPolicy.AlwaysShow, surfacing = listOf("engineering_hub")),
            CatalogRow("fleet.deep_caps", "Deep caps probe", "Fleet", SourceLayer.Product, "deep caps", appStatus = AppStatus.ProbeOnly, visibilityPolicy = VisibilityPolicy.ShowDisabledEngineering),
            CatalogRow("fleet.parity_sweep", "Fleet Parity Sweep", "Fleet", SourceLayer.Product, "parity sweep fps", appStatus = AppStatus.Partial, visibilityPolicy = VisibilityPolicy.ShowDisabledEngineering, surfacing = listOf("engineering_hub")),
            CatalogRow(
                "video.vp9",
                "VP9 WebM video",
                "Video",
                SourceLayer.HalEncoder,
                "vp9 webm",
                appStatus = AppStatus.Shipped,
                surfacing = listOf("format_picker"),
                parityProofScript = "pns_video_format_test.ps1",
                buildPlanSprint = "30.2",
            ),
            CatalogRow("video.dual_iso", "Dual-ISO HDR merge", "Video", SourceLayer.Product, "dual iso hdr", appStatus = AppStatus.ProbeOnly, parityProofScript = "DualIsoVideoMergerTest", buildPlanSprint = "21.3", sweepSkipReason = "probe_only_inventory"),
            CatalogRow(
                "video.uhd60",
                "4K @ 60 fps regular",
                "Video",
                SourceLayer.HalEncoder,
                "uhd60 4k60",
                appStatus = AppStatus.Shipped,
                surfacing = listOf("format_picker"),
                parityProofScript = "pns_mediacodec_hfr_verify.ps1",
                buildPlanSprint = "30.2",
            ),
            CatalogRow(
                "still.heic",
                "HEIC still export",
                "Still capture",
                SourceLayer.Product,
                "heic",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_still_export_verify.ps1",
                buildPlanSprint = "30.1",
            ),
            CatalogRow(
                "still.motion_photo",
                "Motion Photo",
                "Still capture",
                SourceLayer.Product,
                "motion photo",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_still_export_verify.ps1",
                buildPlanSprint = "30.1",
            ),
            CatalogRow(
                "still.tiff16",
                "TIFF 16-bit export",
                "Still capture",
                SourceLayer.Product,
                "tiff 16bit export",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_still_export_verify.ps1",
                buildPlanSprint = "30.1",
            ),
            CatalogRow("video.prores_probe", "ProRes probe", "Video", SourceLayer.Product, "prores anamorphic", appStatus = AppStatus.ProbeOnly),
            CatalogRow("lens.focal_row", "Fleet adaptive focal row", "Lens", SourceLayer.Product, "focal row 7 slot", surfacing = listOf("focal_row")),
            CatalogRow("lens.uw", "Ultra-wide native", "Lens", SourceLayer.Camera2, "uw ultra wide"),
            CatalogRow("lens.wide", "Wide native", "Lens", SourceLayer.Camera2, "wide main"),
            CatalogRow("lens.tele", "Tele native", "Lens", SourceLayer.Camera2, "tele"),
            CatalogRow(
                "dial.monochrome",
                "Monochrome sensor dial",
                "Still capture",
                SourceLayer.Product,
                "monochrome bw dedicated sensor mode",
                appStatus = AppStatus.Shipped,
                visibilityPolicy = VisibilityPolicy.HideWhenUnavailable,
                surfacing = listOf("mode_dial"),
            ),
            CatalogRow(
                "still.monochrome_capture",
                "Monochrome still capture (tiered)",
                "Still capture",
                SourceLayer.Product,
                "monochrome still raw jpeg fallback",
                appStatus = AppStatus.Shipped,
                visibilityPolicy = VisibilityPolicy.ShowDisabledEngineering,
                parityProofScript = "pns_mono_capture_verify.ps1",
                buildPlanSprint = "30.1",
            ),
            CatalogRow("audio.hifi", "Hi-Fi AAC capture", "Audio", SourceLayer.Product, "hifi aac 96k", surfacing = listOf("format_picker")),
            CatalogRow("audio.external_mic", "External mic preference", "Audio", SourceLayer.Product, "external mic usb", surfacing = listOf("format_picker")),
            CatalogRow(
                "audio.spatial",
                "Spatial audio",
                "Audio",
                SourceLayer.Product,
                "spatial audio",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_spatial_audio_verify.ps1",
                buildPlanSprint = "30.3",
            ),
            CatalogRow(
                "preview.pip",
                "Concurrent PiP preview",
                "Preview HUD",
                SourceLayer.Product,
                "pip dual preview",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_pip_preview_verify.ps1",
                buildPlanSprint = "30.3",
            ),
            CatalogRow(
                "video.multicam_melt",
                "Multicam Melt record",
                "Video",
                SourceLayer.Product,
                "multicam melt 4 cam",
                appStatus = AppStatus.Partial,
                parityProofScript = "pns_multicam_melt_verify.ps1",
                buildPlanSprint = "30.3",
            ),
            CatalogRow(
                "capture.wait_focus_lock",
                "Wait for AF lock before still",
                "Still capture",
                SourceLayer.Product,
                "wait focus lock af still",
                appStatus = AppStatus.Shipped,
                surfacing = listOf("settings"),
                parityProofScript = "pns_capture_pipeline_verify.ps1",
                buildPlanSprint = "31.3",
            ),
            CatalogRow(
                "still.panorama",
                "Panorama still",
                "Still capture",
                SourceLayer.Product,
                "panorama sweep stitch",
                appStatus = AppStatus.NotApplicable,
                sweepSkipReason = "panorama_spike_no_go",
                buildPlanSprint = "31.0",
            ),
            CatalogRow(
                "still.preview_shots",
                "Preview Shots sibling clip",
                "Still capture",
                SourceLayer.Product,
                "preview shots sibling mp4",
                appStatus = AppStatus.Planned,
                sweepSkipReason = "post_m28_defer",
                buildPlanSprint = "31.2",
            ),
            CatalogRow(
                "video.log_profile",
                "Log profile video (Open Camera class)",
                "Video",
                SourceLayer.Product,
                "log profile rec709 flat",
                appStatus = AppStatus.NotApplicable,
                sweepSkipReason = "flat_cine_substitute",
                buildPlanSprint = "31.5",
            ),
            CatalogRow(
                "still.ultrahdr",
                "UltraHDR / JPEG-R still",
                "Still capture",
                SourceLayer.Product,
                "ultrahdr gainmap jpegr",
                appStatus = AppStatus.NotApplicable,
                sweepSkipReason = "hal_not_on_primary_fleet",
                buildPlanSprint = "31.6",
            ),
            CatalogRow(
                "still.computational_hdr",
                "Computational HDR still merge",
                "Still capture",
                SourceLayer.Product,
                "computational hdr bracket merge",
                appStatus = AppStatus.Planned,
                sweepSkipReason = "comp_hdr_spike_no_go",
                buildPlanSprint = "31.7",
            ),
            CatalogRow(
                "still.depth",
                "DEPTH still export",
                "Still capture",
                SourceLayer.Camera2,
                "depth map still",
                appStatus = AppStatus.ProbeOnly,
                visibilityPolicy = VisibilityPolicy.ShowDisabledEngineering,
                sweepSkipReason = "post_m28_defer",
                buildPlanSprint = "32.1",
            ),
            CatalogRow(
                "preview.qr_mlkit",
                "ML Kit QR backend (optional)",
                "Preview HUD",
                SourceLayer.Product,
                "mlkit qr barcode",
                appStatus = AppStatus.Planned,
                sweepSkipReason = "zxing_default_foss",
                buildPlanSprint = "32.2",
            ),
            CatalogRow("product.format_picker", "Format quality picker", "Fleet", SourceLayer.Product, "format picker cqi", surfacing = listOf("format_picker")),
            CatalogRow(
                "product.still_image_camera_launch",
                "STILL_IMAGE_CAMERA launch handler",
                "Fleet",
                SourceLayer.Product,
                "still image camera launch intent",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_fleet_matrix_scan.ps1",
            ),
            CatalogRow(
                "product.still_image_camera_secure_launch",
                "STILL_IMAGE_CAMERA_SECURE launch handler",
                "Fleet",
                SourceLayer.Product,
                "still image camera secure launch intent",
                appStatus = AppStatus.Shipped,
                parityProofScript = "pns_lockscreen_camera_verify.ps1",
            ),
            CatalogRow(
                "product.hardware_camera_key",
                "Dedicated hardware camera key",
                "Fleet",
                SourceLayer.Product,
                "hardware camera key shutter focus",
                appStatus = AppStatus.Partial,
                surfacing = listOf("settings"),
                parityProofScript = "pns_hardware_key_probe.ps1",
            ),
            CatalogRow(
                "product.programmable_hardware_button",
                "Programmable hardware button",
                "Fleet",
                SourceLayer.Product,
                "shortcut key side button programmable",
                appStatus = AppStatus.Partial,
                parityProofScript = "pns_hardware_key_probe.ps1",
                sweepSkipReason = "interactive_probe_required",
            ),
            CatalogRow("tether.http", "Tether HTTP status", "Fleet", SourceLayer.Product, "tether http"),
            CatalogRow("tether.wifi_direct", "Wi-Fi Direct tether", "Fleet", SourceLayer.Product, "wifi direct"),
            CatalogRow(
                "privacy.exif_strip",
                "EXIF privacy strip",
                "Privacy",
                SourceLayer.Product,
                "exif strip privacy gps make model metadata",
                appStatus = AppStatus.Shipped,
                surfacing = listOf("settings"),
                parityProofScript = "pns_exif_strip_verify.ps1",
                buildPlanSprint = "29.1",
            ),
            CatalogRow(
                "product.settings_export",
                "Settings export / import",
                "Fleet",
                SourceLayer.Product,
                "settings export import saf json backup",
                appStatus = AppStatus.Shipped,
                surfacing = listOf("settings"),
                parityProofScript = "pns_settings_export_verify.ps1",
                buildPlanSprint = "29.2",
            ),
        )

    val registry: List<CatalogRow> =
        (baseRegistry + CameraCapabilityCatalogExpansion.expandedRows()).distinctBy { it.id }
}
